"""
Generate the econ icon stylesheet: gloves, pins and music kits.

One class per glove finish, pointing at CS2's OWN econ art through the `s2r://` protocol:

    background-image: url("s2r://panorama/images/econ/default_generated/<glove>_<kit>_light.png");

docs/ARSENAL.md previously recorded that Valve's econ art was unreachable from a
custom_hud_layout. That was wrong, and specifically it was wrong about the PROTOCOL: the
addon-relative forms (`file://{images}`, `{resources}/images`) genuinely do not work, but
`s2r://` resolves against the game's own resource system and does. Credit to cs2-hudkit for
the find.

The art is referenced as `.png` even though it is filed in pak01 as `_png.vtex_c`; that is the
same rewrite the compiler does for our own images.

SIZE MATTERS. CreateLayout parses every included stylesheet server side, and cs2-hudkit records
that a 63k-rule sheet froze the server outright. 94 rules is nothing, but do not be tempted to
generate the same thing for all 2017 weapon finishes without measuring it first.
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(HERE, "..", "v5-skins", "panorama", "styles", "custom_game", "econicons.css")
SKINS = "s2r://panorama/images/econ/default_generated"
IMAGES = "s2r://panorama/images"


def build():
    lines = [
        "/* Generated by tools/gen_econ_icons.py - do not edit by hand. */",
        "/* CS2's own econ art, reached with s2r://. Nothing is shipped with the plugin. */",
        "",
        ".EconIcon { width: 100%; height: 100%; background-size: contain;"
        " background-repeat: no-repeat; background-position: 50% 50%; }",
        "",
    ]
    n = 0

    # Gloves key on the PAINT index, because a glove is a glove plus a finish, and their art is
    # filed under default_generated like every weapon skin.
    gloves = json.load(io.open(os.path.join(HERE, "armory_gloves.json"), encoding="utf-8"))

    for glove, v in sorted(gloves.items()):
        for f in v["finishes"]:
            stem = f"{glove}_{f['k']}_light"
            lines.append(f'.EconIcon.g{f["i"]} {{ background-image: url("{SKINS}/{stem}.png"); }}')
            n += 1

    # PINS key on the item definition index, and their art lives under status_icons.
    econ_path = os.path.join(HERE, "..", "..", "Armory", "configs", "armory_econ.json")
    econ = json.load(io.open(os.path.abspath(econ_path), encoding="utf-8"))

    for idx, e in econ.items():
        if "/status_icons/" not in e["img"]:
            continue

        lines.append(f'.EconIcon.p{idx} {{ background-image: url("{IMAGES}/{e["img"]}.png"); }}')
        n += 1

    # MUSIC KITS key on the music_definitions id, which is a DIFFERENT keyspace from item
    # definitions - keying these off the item list produced classes that could never match, and
    # the preview came up blank.
    music = json.load(io.open(os.path.join(HERE, "armory_music.json"), encoding="utf-8"))

    for group in sorted(music):
        for e in music[group]:
            lines.append(f'.EconIcon.m{e["i"]} {{ background-image: url("{IMAGES}/{e["img"]}.png"); }}')
            n += 1

    dest = os.path.abspath(DEST)
    io.open(dest, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {dest} - {n} icon classes, {os.path.getsize(dest)} bytes")


if __name__ == "__main__":
    build()
