"""
Emit panorama/layout/custom_game/skins.xml for ARMORY / ARSENAL.

Generated rather than hand-written because each column declares 72 rows.

Why 72 and why no pagers:

    weapons              55  -> fits
    finishes per weapon  60  -> fits (worst is weapon_ak47)
    collections          65  -> fits
    stickers per coll  1404  -> does NOT fit, median is 21

custom_hud_layout has NO scroll or wheel event - InstallClickListener is the whole
input surface - so the server can never be told about a wheel. It does not need to
be: a panel with `overflow: squish scroll` scrolls on the CLIENT with no server
involvement. The only requirement is that the row exists in the XML. At 72 rows
every list except the big tournament sticker capsules fits whole, so the pagers are
gone everywhere else; the sticker pager appears only when the server says the
collection overflows.

Panorama, not web:
  * only <Panel> / <Label> / <Image> / <Button> exist
  * `hittest` is DISALLOWED on <Button>, and one bad attribute fails the WHOLE layout
  * the root <Panel> may not carry an id
"""
import io
import os

ROWS = 72


def rows(prefix):
    out = []
    for i in range(ROWS):
        out.append(
            '\t\t\t\t<Button id="{p}{i}" class="Row">\n'
            '\t\t\t\t\t<Label id="{p}{i}_n" class="RowN" text="{{s:v}}" />\n'
            '\t\t\t\t\t<Label id="{p}{i}_l" class="RowL" text="{{s:v}}" />\n'
            '\t\t\t\t\t<Label id="{p}{i}_m" class="RowM" text="{{s:v}}" />\n'
            '\t\t\t\t</Button>'.format(p=prefix, i=i))
    return "\n".join(out)


def nudge(gid, cap, unit=""):
    unit_el = ('\n\t\t\t\t<Label class="Unit" text="%s" />' % unit) if unit else ""
    return (
        '\t\t\t<Panel class="Grp" hittest="false">\n'
        '\t\t\t\t<Label class="Cap" text="{cap}" />\n'
        '\t\t\t\t<Button id="{g}_l" class="Step"><Label class="StepL" text="&#8722;" /></Button>\n'
        '\t\t\t\t<Label id="{g}_v" class="Val" text="{{s:v}}" />\n'
        '\t\t\t\t<Button id="{g}_r" class="Step"><Label class="StepL" text="&#43;" /></Button>{u}\n'
        '\t\t\t</Panel>'.format(cap=cap, g=gid, u=unit_el))


def column(side, secid, listid, prefix, pager):
    pager_xml = ""
    if pager:
        pager_xml = (
            '\n\t\t\t<Panel id="fn_pager" class="Pager" hittest="false">\n'
            '\t\t\t\t<Button id="fn_prev" class="Step"><Label class="StepL" text="&#9664;" /></Button>\n'
            '\t\t\t\t<Label id="fn_page" class="Val" text="{s:v}" />\n'
            '\t\t\t\t<Button id="fn_next" class="Step"><Label class="StepL" text="&#9654;" /></Button>\n'
            '\t\t\t</Panel>')
    return (
        '\t\t<Panel class="Scrim {side}Scrim" hittest="false" />\n'
        '\t\t<Panel class="Col {side}" hittest="false">\n'
        '\t\t\t<Panel class="ColHead" hittest="false">\n'
        '\t\t\t\t<Label class="HeadIdx" text="IDX" />\n'
        '\t\t\t\t<Panel class="HeadTick" hittest="false" />\n'
        '\t\t\t\t<Label id="{sec}" class="Sec" text="{{s:v}}" />\n'
        '\t\t\t\t<Panel class="HeadRule" hittest="false" />\n'
        '\t\t\t\t<Label id="{sec}_c" class="HeadN" text="{{s:v}}" />\n'
        '\t\t\t</Panel>\n'
        '\t\t\t<Panel id="{list}" class="Scroll">\n'
        '{rows}\n'
        '\t\t\t</Panel>{pager}\n'
        '\t\t</Panel>'.format(side=side, sec=secid, list=listid, rows=rows(prefix), pager=pager_xml))


LAYOUT = '''<!--
  ARMORY / ARSENAL - the in-game weapon skin browser.

  Generated by tools/gen_layout.py - edit that, not this.

  Structure carries no containers: hairline rules cut to length, a focused row marked
  by its own rule running long and turning accent, and monospaced readouts with unit
  labels. No filled panels, no accent bar down the row edge, no rivets.

  Each column declares 72 rows inside `overflow: squish scroll`, so weapons (55),
  finishes (max 60) and collections (65) scroll whole with no pager at all. Only the
  sticker list can overflow - the biggest tournament capsule is 1404 - so it alone
  keeps one, and the server hides it when the collection fits.

  THE MIDDLE IS EMPTY ON PURPOSE: a real weapon entity renders back there and Panorama
  always draws above the world.

  `hittest` is DISALLOWED on <Button> and one disallowed attribute fails the ENTIRE
  layout closed; the root Panel may not carry an id.
-->
<root>
\t<styles>
\t\t<include src="file://{resources}/styles/custom_game/skins.css" />
\t\t<include src="file://{resources}/styles/custom_game/econicons.css" />
\t</styles>

\t<Panel class="RootWrap">
\t<Panel id="root" class="Root Closed">

\t\t<Panel class="Ground" hittest="false" />
		<Panel class="TopFade" hittest="false" />
		<Panel class="BotFade" hittest="false" />

\t\t<Panel class="Head" hittest="false">
\t\t\t<Label class="Kick" text="ARMORY / ARSENAL" />
\t\t\t<Label id="title" class="Title" text="{s:v}" />
\t\t</Panel>

\t\t<Panel class="Spine" hittest="false">
\t\t\t<Label id="idx" class="SpineN" text="{s:v}" />
\t\t\t<Panel class="SpineRule" hittest="false" />
\t\t\t<Label class="SpineT" text="SKIN" />
\t\t</Panel>

\t\t<!-- Glove mode has no 3D preview: a glove is worn, and the client only resolves one when
\t\t     the pawn is built. This shows CS2's own econ art for the selected finish instead, which
\t\t     the server picks by putting a g<paintIndex> class on it. -->
\t\t<Panel id="econ_shot" class="EconShot Hide" hittest="false">
\t\t\t<Panel id="econ_icon" class="EconIcon" hittest="false" />
\t\t\t<!-- Panorama plays a soundevent the moment a class carrying `sound:` is applied, so
\t\t\t     toggling one of the k<id> classes here previews a music kit. -->
\t\t\t<Panel id="music_play" class="MusicPlay" hittest="false" />
\t\t</Panel>

\t\t<!-- OUTSIDE econ_shot on purpose: that panel is hittest="false", so a button inside it
\t\t     could never be clicked, and a child sitting past its edge on a negative margin gets
\t\t     clipped. -->
\t\t<!-- A transport bar rather than a lone button: the kit it belongs to is written on it, so
\t\t     the control and the thing it controls read as one object instead of two scattered ones. -->
\t\t<Panel id="deck" class="Deck Hide" hittest="false">
\t\t\t<Panel class="DeckPlate" hittest="false" />
\t\t\t<Panel class="DeckRail" hittest="false" />
\t\t\t<Panel class="DeckBody" hittest="false">
\t\t\t\t<Label class="DeckCap" text="NOW PLAYING" />
\t\t\t\t<Label id="deck_name" class="DeckName" text="{s:v}" />
\t\t\t</Panel>
\t\t\t<Button id="btn_listen" class="Listen">
\t\t\t\t<Label id="btn_listen_g" class="ListenGlyph" text="{s:v}" />
\t\t\t</Button>
\t\t</Panel>

\t\t<Panel class="Readout" hittest="false">
\t\t\t<Label id="skinname" class="SkinName" text="{s:v}" />
\t\t\t<Panel class="ReadRow" hittest="false">
\t\t\t\t<Panel class="ReadTick" hittest="false" />
\t\t\t\t<Label id="skinrarity" class="SkinRarity" text="{s:v}" />
\t\t\t\t<Panel class="ReadTick" hittest="false" />
\t\t\t</Panel>
\t\t</Panel>

COLUMNS

\t\t<Panel class="Corner" hittest="false">
\t\t\t<Button id="btn_weapons" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="WEAPONS" /></Button>
\t\t\t<Button id="btn_knives" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="KNIVES" /></Button>
\t\t\t<Button id="btn_gloves" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="GLOVES" /></Button>
\t\t\t<Button id="btn_pins" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="PINS" /></Button>
\t\t\t<Button id="btn_music" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="MUSIC" /></Button>
\t\t\t<Button id="btn_equip" class="Tag TagGo"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="EQUIP" /></Button>
\t\t\t<Button id="btn_close" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="ESC" /></Button>
\t\t</Panel>

\t\t<Label id="equipped" class="Equipped" text="{s:v}" />

\t\t<Panel class="Dock" hittest="false">
\t\t\t<Panel class="DockRule" hittest="false" />

\t\t\t<Panel id="stk_row" class="DockRow" hittest="false">
\t\t\t\t<Label class="Cap" text="SLOT" />
SLOTS
\t\t\t\t<Panel class="VRule" hittest="false" />
FIELDS
\t\t\t\t<Panel class="VRule" hittest="false" />
\t\t\t\t<Button id="stk_clear" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="CLR" /></Button>
\t\t\t</Panel>

\t\t\t<Panel id="view_row" class="DockRow DockView" hittest="false">
\t\t\t\t<Button id="btn_mode" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="STICKERS" /></Button>
\t\t\t\t<Panel class="VRule" hittest="false" />
VIEW
\t\t\t\t<Button id="view_reset" class="Tag"><Panel class="TagSkew" hittest="false" /><Label class="TagL" text="RESET" /></Button>
\t\t\t</Panel>
\t\t</Panel>

\t\t<Panel class="Brand" hittest="false">
\t\t\t<Image class="BrandImg" src="file://{images}/armory/cstema.png" />
\t\t</Panel>

\t</Panel>
\t</Panel>
</root>
'''

if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))

    columns = (column("ColL", "sec_l", "list_l", "wp", pager=False) + "\n\n"
               + column("ColR", "sec_r", "list_r", "fn", pager=True))

    slots = "\n".join(
        '\t\t\t\t<Button id="stkslot%d" class="Chip"><Label class="ChipL" text="%d" /></Button>' % (i, i + 1)
        for i in range(5))

    fields = "\n".join([nudge("stk_x", "X", "U"), nudge("stk_y", "Y", "U"),
                        nudge("stk_r", "ROT", "DEG"), nudge("stk_s", "WEAR", "FV")])

    view = "\n".join([nudge("rot", "TURN", "DEG"), nudge("zoom", "ZOOM"),
                      nudge("panx", "MOVE X"), nudge("pany", "MOVE Y")])

    xml = (LAYOUT.replace("COLUMNS", columns)
                 .replace("SLOTS", slots)
                 .replace("FIELDS", fields)
                 .replace("VIEW", view))

    dest = os.path.join(here, "..", "panorama", "layout", "custom_game", "skins.xml")
    dest = os.path.abspath(dest)
    with io.open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(xml)
    print("wrote %s (%d bytes, %d rows/column)" % (dest, os.path.getsize(dest), ROWS))
